name: Test deployment

on:
  push:
    branches:
      - main
    paths:
      - 'sop-website/**'

jobs:
  test-deploy:
    name: Test deployment
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: sop-website
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          
      # Install and build Docusaurus website
      - name: Build site
        run: |
          # cd sop-website
          npm install
          npm run build
